name: Formatting check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  fmt-check:
    name: Check Go Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Check formatting with gofmt
        run: |
          fmt_output=$(gofmt -l .)
          if [ -n "$fmt_output" ]; then
            echo "Following files need formatting: "
            echo "$fmt_output"
            exit 1
          else
            echo "All files are formatted properly"
          fi

